### ISSUE TITLE
Not able to fetch secret values form Linked Keyvault variable groups in DevOps

### ISSUE THREAD

**Issue by jitheshksn** [SQLPlayer/azure.datafactory.devops#39]
We are trying to use this plug-in in our Azure DevOps. Everything is fine except for fetching secrets from KeyVault for Linked Services. We are getting blank value during deployment. 
Please attached screenshots. 
![DevOpsError](https://user-images.githubusercontent.com/7765184/113278293-6395a780-92ff-11eb-8140-083c59a9b4e3.jpg)

![MicrosoftTeams-image (12)](https://user-images.githubusercontent.com/7765184/113278041-0ac60f00-92ff-11eb-979b-f260e981d9b3.png)

How can we fetch secrets from KV? Is there any option available?

**Comment by NowinskiK** [comment]
This is because secret variables must be mapped in "Environment variables" section. 
Example:
![image](https://user-images.githubusercontent.com/25029325/113293362-920a8700-92ed-11eb-9591-3a46f0768719.png)
More info: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=classic%2Cbatch#secret-variables
